### ISSUE TITLE
Multi-thread has conflict with Nexpy

### ISSUE THREAD

**Issue by Henry0422** [Beamlines-CanadianLightSource/SGM_Nexpy#8]
I implemented the multi-thread code for gathering 4 SDDs from the data file, but it has some issues related to `NeXusError: Cannot read data for 'sdd3'`

Here is the error messages I got, and you can just download the source code from [multi_thread](https://github.com/Beamlines-CanadianLightSource/SGM_Nexpy/tree/multi_thread) branch to reproduce these issues. 

**I really appreciate if someone can help me look into this.**

```
C:\Users\hanr>nexpy
Thread 1 started
Thread 2 started
Thread 3 started
Thread 4 started
check1--- 0.039999961853 seconds ---
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\lib\threading.py", line 801, in __bootstrap_i
nner
    self.run()
  File "C:\Program Files\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\hanr\.nexpy\plugins\SGM_Nexpy\multi_xas.py", line 35, in get_sd
d3
    list3.append(np.array(np.array(filename.NXentry[i].instrument.fluorescence.s
dd3)))
  File "C:\Program Files\Anaconda2\lib\site-packages\nexusformat\nexus\tree.py",
 line 2137, in __array__
    return np.asarray(self.nxdata)
  File "C:\Program Files\Anaconda2\lib\site-packages\nexusformat\nexus\tree.py",
 line 2476, in nxdata
    raise NeXusError("Cannot read data for '%s'" % self.nxname)
NeXusError: Cannot read data for 'sdd3'

Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\lib\threading.py", line 801, in __bootstrap_i
nner
    self.run()
  File "C:\Program Files\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\hanr\.nexpy\plugins\SGM_Nexpy\multi_xas.py", line 27, in get_sd
d2
    list2.append(np.array(np.array(filename.NXentry[i].instrument.fluorescence.s
dd2)))
  File "C:\Program Files\Anaconda2\lib\site-packages\nexusformat\nexus\tree.py",
 line 2137, in __array__
    return np.asarray(self.nxdata)
  File "C:\Program Files\Anaconda2\lib\site-packages\nexusformat\nexus\tree.py",
 line 2476, in nxdata
    raise NeXusError("Cannot read data for '%s'" % self.nxname)
NeXusError: Cannot read data for 'sdd2'

Length of list1: 10
check2--- 0.0999999046326 seconds ---
Length of list4: 10
check3--- 0.119999885559 seconds ---
check4--- 0.129999876022 seconds ---
check5--- 0.139999866486 seconds ---
check6--- 0.139999866486 seconds ---
111--- 0.139999866486 seconds ---
Traceback (most recent call last):
  File "C:\Users\hanr\.nexpy\plugins\SGM_Nexpy\xas_multi.py", line 365, in plot_
sum
    self.xas.getpfy(self.roi_dn, self.roi_up)
  File "C:\Users\hanr\.nexpy\plugins\SGM_Nexpy\multi_xas.py", line 168, in getpf
y
    [self.pfy_sdd2[i].append(np.sum(self.sdd2[i][j][roi_start:roi_end])) for i i
n np.arange(0, sdd_length) for j in np.arange(0, len(self.sdd2[i]))]
IndexError: list index out of range
```

**Comment by znarthur** [comment]
I think the default version of h5py (which is used by nexpy) only allows a single reader at a time.  What we are seeing here is probably the result of a collision of threads trying to access the file.   It looks like the native parallel read method is using  [mpi4py](http://docs.h5py.org/en/latest/mpi.html).

It may be that multiprocessing and threading will be difficult to incorporate without forcing the load of the whole file into memory first.

**Comment by znarthur** [comment]
Actually, upon second thought, it looks like the HDF group is planning on releasing a multiple read update to the hdf5 library.  See the page on [SWMR](http://docs.h5py.org/en/latest/swmr.html)
