### ISSUE TITLE
Multiprocessing code not compatible with Windows

### ISSUE THREAD

**Issue by Henry0422** [Beamlines-CanadianLightSource/SGM_Nexpy#9]
I can run multiprocessing code on my personal macbook with `Python 2.7.12`, but when I run the exactly same code on Windows with Python `2.7.13`. It returns weird errors...

To reproduce this issue, run the source code from [multi_processing ](https://github.com/Beamlines-CanadianLightSource/SGM_Nexpy/tree/multi_processing) branch

C:\Users\hanr>nexpy
check1--- 0.0 seconds ---
check2--- 0.0199999809265 seconds ---
check3--- 0.0209999084473 seconds ---
check4--- 0.0419998168945 seconds ---
check5--- 0.0519998073578 seconds ---
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Anaconda2\lib\multiprocessing\forking.py", line 381,
 main
    self = load(from_parent)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 1130, in find_class
    __import__(module)
ImportError: No module named SGM_Nexpy.multi_xas
Traceback (most recent call last):
  File "C:\Users\hanr\.nexpy\plugins\SGM_Nexpy\xas_multi.py", line 362, in pl
sum
    self.xas = multi_xas.getMultiXAS(self.root, range_start = self.start, ran
end = self.end)
  File "C:\Users\hanr\.nexpy\plugins\SGM_Nexpy\multi_xas.py", line 49, in get
tiXAS
    Process(target=get_sdd1, args=(filename, range_array, return_dict)).start
  File "C:\Program Files\Anaconda2\lib\multiprocessing\process.py", line 130,
 start
    self._popen = Popen(self)
  File "C:\Program Files\Anaconda2\lib\multiprocessing\forking.py", line 277,
 __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Program Files\Anaconda2\lib\multiprocessing\forking.py", line 199,
 dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 687, in _batch_setite
    save(v)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 554, in save_tuple
    save(element)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 687, in _batch_setite
    save(v)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 687, in _batch_setite
    save(v)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 687, in _batch_setite
    save(v)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 687, in _batch_setite
    save(v)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 687, in _batch_setite
    save(v)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 687, in _batch_setite
    save(v)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 687, in _batch_setite
    save(v)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 692, in _batch_setite
    save(v)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 687, in _batch_setite
    save(v)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 568, in save_tuple
    save(element)
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Anaconda2\lib\pickle.py", line 492, in save_string
    self.write(BINSTRING + pack("<i", n) + obj)
IOError: [Errno 22] Invalid argument

**Comment by znarthur** [comment]
I had similiar problems on my first and only attempt to implement the multiprocessing library,  it seems like from these errors that upon execution the multiprocessing doesn't preserve the path environment.  So it can't find the plugin python files.    I wonder if including the plugin path using something like `os.environ["PATH"] += os.pathsep + path` would remedy the problem.
